### ISSUE TITLE
Must this only be used with laptops?

### ISSUE THREAD

**Issue by TheMangoTrain** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#10]
Is it really laptop specific?

I have desktop box with an MSI mortar motherboard, B550 bios.

**Comment by YoCodingMonster** [comment]
this is laptop-specific as desktop have less to no issue with thermals and fan control when it comes to ubuntu or any Linux distro. Fan curves are bios controlled
