### ISSUE TITLE
V1.3.1

### ISSUE THREAD

**Issue by robouden** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#14]
Version 1.3.1 works nice!! Thanks for keeping up the updates.

A few things I would like to suggest for changing:

- [ ] The credit should be in an about link/button not on the main page (looks unprofessional)
- [ ] Link to GitHub for more information/versions etc.
- [ ] Rename monitering to monitoring.
- [ ] being able to set minimum speed of the fans (I know that is hard to do). I would love to have my GS66 at lowest speed be 2100 instead of now 2700 RPM.

**Comment by YoCodingMonster** [comment]
> Version 1.3.1 works nice!! Thanks for keeping up the updates.
> 
> A few things I would like to suggest for changing:
> 
> - [ ] The credit should be in an about link/button not on the main page (looks unprofessional)
> - [ ] Link to GitHub for more information/versions etc.
> - [ ] Rename monitering to monitoring.
> - [ ] being able to set minimum speed of the fans (I know that is hard to do). I would love to have my GS66 at lowest speed be 2100 instead of now 2700 RPM.

Fixed the typo right away😅
The buttons for GitHub and credits will be made as requested.
Being able to set the speed manually is a nice idea for advanced users...I will think of some creative ideas to make it safe and easy.

Thanks by the way!!!
You are a major contributed to this projects when it comes to ideas and new things!!
