### ISSUE TITLE
Not working on Arch Linux Qtile

### ISSUE THREAD

**Issue by siu-temp-schoolaccount** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#15]
This is probably going to be a niche problem but after installing all of the dependencies and running the app as specified, I get this error:

`Traceback (most recent call last):
  File "/home/weiseguy/MSI-Dragon-Center-for-Linux/GUI-MSI-DC-L.py", line 46, in <module>
    window = Tk()
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display ":0"`

This is probably because I run a tiling window manager and nothing else. 
My motherboard info is:
`Micro-Star International Co., Ltd.
MS-16P6
REV:1.0`

**Comment by YoCodingMonster** [comment]
> This is probably going to be a niche problem but after installing all of the dependencies and running the app as specified, I get this error:
> 
> `Traceback (most recent call last):
>   File "/home/weiseguy/MSI-Dragon-Center-for-Linux/GUI-MSI-DC-L.py", line 46, in <module>
>     window = Tk()
>   File "/usr/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
>     self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
> _tkinter.TclError: couldn't connect to display ":0"`
> 
> This is probably because I run a tiling window manager and nothing else. 
> My motherboard info is:
> `Micro-Star International Co., Ltd.
> MS-16P6
> REV:1.0`

Dude, this software is for laptops only!!
And if you do get it running...I don't knwo if you can control fans and moniter with this...

But the error seems to be related to tkinter which is irrelevant of laptop or desktop.

So, this is a problem of type is window managment system you are running.
