### ISSUE TITLE
Fan mode working great on ubuntu 21.04! Msi prestige 15 EVO (i7,16gb,1650ti)

### ISSUE THREAD

**Issue by feduss** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#16]
I don't know how much fans are in my notebook, but your tool shows only a gpu fan working. 
Temperatures (both cpu and gpu) working.
I didn't test battery thresholds, but it shows wrong battery % (100% all the time) and wrong threashold (10%...on windows i've set 80%).

Thanks for your work!

![screen1](https://user-images.githubusercontent.com/1686561/119883021-57a91900-bf2f-11eb-8cd0-b4e244f89f90.png)

**Comment by YoCodingMonster** [comment]
Battery Threshold section is in beta.

for fans not working, try the latest release!!
which i am gonna do in just few minutes. wait and then download it!

**Comment by feduss** [comment]
cool! Thanks! i will :)

**Comment by feduss** [comment]
@YoCodingMonster fan mode and monitoring don't work with last release.

**Comment by YoCodingMonster** [comment]
You need to provide them with the sude permissions to read and write to EC files

**Comment by feduss** [comment]
how? i run sudo ./at_startup.sh and then it gives me the nohup.out error

**Comment by YoCodingMonster** [comment]
> how? i run sudo ./at_startup.sh and then it gives me the nohup.out error

No sudo required this time for app to work
Just type
./at_startup.sh

**Comment by YoCodingMonster** [comment]
Did it work @feduss ?

**Comment by neel2902** [comment]
@feduss 
You can give execute permissions to scripts using these commands:
`chmod` +x /path/to/yourscript.sh`

And to run your script:
`/path/to/yourscript.sh`

**Comment by feduss** [comment]
sorry for late reply, i didn't use ubuntu for few days...btw, running only ./at_startup.sh gives me the following errors, even with chmod +x

nohup: opening of 'nohup.out' failed: Permission denied
nohup: opening of '/home/feduss/nohup.out' failed: Permission denied

**Comment by YoCodingMonster** [comment]
> sorry for late reply, i didn't use ubuntu for few days...btw, running only ./at_startup.sh gives me the following errors, even with chmod +x
> 
> nohup: opening of 'nohup.out' failed: Permission denied
> nohup: opening of '/home/feduss/nohup.out' failed: Permission denied

I just saw your message and will be addressing this with some other issues in a couple of days.!!
