### ISSUE TITLE
Slient logging

### ISSUE THREAD

**Issue by sangramsingha** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#18]
Your work is awesome.. loved it.
Working on 

```
System:    Kernel: 5.8.0-53-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 4.8.6 Distro: Linux Mint 20.1 Ulyssa 
                 base: Ubuntu 20.04 focal
Machine:   Type: Laptop System: Micro-Star product: Modern 14 B4MW v: REV:1.0 serial: <filter> 
                  Mobo: Micro-Star model: MS-14DK v: REV:1.0 serial: <filter> UEFI: American Megatrends v: E14DKAMS.112 
                  date: 01/25/2021
```
M running version 1.4 of OpenFreezeCenter.

Every time i click on a button like moniter, fan control. It opens up a terminal with message
`nohup: ignoring input and appending output to 'nohup.out'`. 
Can you please silently log that message into a file instead of opening a  terminal?

Just in case you are interested. Here is a exception on my machine
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "monitor.py", line 94, in monitoring_int
    color(temp_c, lable_c22)
  File "monitor.py", line 112, in color
    lable.config(text = temp, fg = 'green', bg = 'black' if mode == 1 else 'light grey')
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main loop
```

The application has considerable delay.

Also i would like to buy you a beer (drop me a mail). It is a nice work.

**Comment by YoCodingMonster** [comment]
new version 2 will fix all the delay and silent logging will be a thing!!
there are many other things planned for that version.

will be out in a couple of days!!

**Comment by YoCodingMonster** [comment]
@sangramsingha 
Check this new update. it's all new and fast. with minimal code copy paste for now!!
