### ISSUE TITLE
Line  120.126,146,154 in GUI-MSI-DC-L.py

### ISSUE THREAD

**Issue by volnes** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#3]
Lines  120, 126, 146, 154 command above "gnome-terminal -e 'bash -c" It is desirable to unify, because not all users use Gnome and gnome terminal

**Comment by YoCodingMonster** [comment]
Will consider that.thankyou

**Comment by MaximoMachado** [comment]
Just wanted to bump this, I can't launch Alacritty after installing this.

**Comment by YoCodingMonster** [comment]
> Just wanted to bump this, I can't launch Alacritty after installing this.

Can you tell me the exact error it shows or is it just refusing to open?

**Comment by MaximoMachado** [comment]
It was refusing to open. Though this might be something related, somehow snapd got uninstalled from my system and so I had to reinstall it and everything started opening again. Not entirely sure why but potentially unrelated, potentially not. It did happen right after I installed the software and restarted my computer though.

**Comment by YoCodingMonster** [comment]
> It was refusing to open. Though this might be something related, somehow snapd got uninstalled from my system and so I had to reinstall it and everything started opening again. Not entirely sure why but potentially unrelated, potentially not. It did happen right after I installed this software and restarted my computer though.

It might be due to the fact that Writing on EC needs the secure boot to be disabled!

**Comment by volnes** [comment]
@YoCodingMonster Hello! u still not unify it? i mean "gnome-terminal -e"
well put this:
`x-terminal-emulator -e`
or
`xterm -e`

Both things are universal for any distro.
Thanks

**Comment by YoCodingMonster** [comment]
> @YoCodingMonster Hello! u still not unify it? i mean "gnome-terminal -e"
> well put this:
> `x-terminal-emulator -e`
> or
> `xterm -e`
> 
> Both things are universal for any distro.
> Thanks

Next version....it will be done..
Promiss👍🏻

**Comment by volnes** [comment]
> > @YoCodingMonster Hello! u still not unify it? i mean "gnome-terminal -e"
> > well put this:
> > `x-terminal-emulator -e`
> > or
> > `xterm -e`
> > Both things are universal for any distro.
> > Thanks
> 
> Next version....it will be done..
> Promiss👍🏻

u need to post about your project on reddit
https://www.reddit.com/r/linux/
and
https://www.reddit.com/r/linux_gaming/
There a lot of people who can help to improve it and there a lot of people who will be thankful for your work too.

**Comment by YoCodingMonster** [comment]
> > > @YoCodingMonster Hello! u still not unify it? i mean "gnome-terminal -e"
> > > well put this:
> > > `x-terminal-emulator -e`
> > > or
> > > `xterm -e`
> > > Both things are universal for any distro.
> > > Thanks
> > 
> > Next version....it will be done..
> > Promiss👍🏻
> 
> u need to post about your project on reddit
> https://www.reddit.com/r/linux/
> and
> https://www.reddit.com/r/linux_gaming/
> There a lot of people who can help to improve it and there a lot of people who will be thankful for your work too.
> 

Sure bro..
Will do it right away

**Comment by volnes** [comment]
@YoCodingMonster close this issue. U do a good work.

**Comment by volnes** [comment]
and add laptop MSI GF63-Thin your app works good on Ubuntu Mate 20.04

**Comment by volnes** [comment]
@YoCodingMonster and add laptop MSI GF63-Thin to readme
