### ISSUE TITLE
Can not install in arch kde plasma

### ISSUE THREAD

**Issue by Ritul13** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#4]
I have downloaded the zip. File and run in the termi al. But can not install... Please help. Me it will be big help. For me

**Comment by marshevms** [comment]
Can you please test https://github.com/marshevms/mlfc?

**Comment by YoCodingMonster** [comment]
> I have downloaded the zip. File and run in the termi al. But can not install... Please help. Me it will be big help. For me

Can you share a screenshot of the error you got
