### ISSUE TITLE
Very nice app. Got it working on Linux Mint 20.1 on MSI GS66

### ISSUE THREAD

**Issue by robouden** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#6]
Thanks for all this nice work on the GUI.

A few question about customizing. (I am not so familiar with  to Python):

1) Instead of having to push the buttons on the screen, can I set the canvas starting with Monitoring and Fan Modes visual?
2) How to run it as  an icon in on a panel?
3) any simple way to have a dark mode option?

Regards,
Rob Oudendijk

**Comment by YoCodingMonster** [comment]
Thanks for appriciation

Dark mode is a good idea..thanks..will impliment it in the next release version..

Integrating it as an icon in the panel is a task which will be released in version 2.. soo it's a wait of about 2 to 3 months as this software runs from console

Having to see monitering and fancurves by default will be integrated soon...

**Comment by YoCodingMonster** [comment]
> Thanks for all this nice work on the GUI.
> 
> A few question about customizing. (I am not so familiar with  to Python):
> 
> 1) Instead of having to push the buttons on the screen, can I set the canvas starting with Monitoring and Fan Modes visual?
> 2) How to run it as  an icon in on a panel?
> 3) any simple way to have a dark mode option?
> 
> Regards,
> Rob Oudendijk

New version out...with dark mode!!

**Comment by robouden** [comment]
I wil check it!!

**Comment by robouden** [comment]
Much better! Thanks for putting up the new version.  I moded a bit with the colors and layout
![Screenshot from 2021-05-12 12-15-25](https://user-images.githubusercontent.com/1387190/117913717-d2154e80-b31c-11eb-93a5-54eea0115de2.png)

**Comment by YoCodingMonster** [comment]
Great bro

**Comment by robouden** [comment]
One more idea/option to have the program start up in the last applied mode. I always like to start in auto mode for example.

**Comment by YoCodingMonster** [comment]
ok can add that too

**Comment by robouden** [comment]
Maybe one other idea is to have the last settings saved in the config.txt on pressing the apply button?

**Comment by YoCodingMonster** [comment]
Working on that....will be released with version 1.3.1
