### ISSUE TITLE
List of tested models

### ISSUE THREAD

**Issue by RushanKhan1** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#7]
Can we have a community-maintained list of all the models that this software works on and doesn't work on?
* People who try this app can update it with their models, and their experience.
*  This would help people to unhesitatingly install it if their model has already been tested or not install it if the software didn't seem to work on their model.

**Comment by YoCodingMonster** [comment]
Yes that is awsome
