### ISSUE TITLE
Run at Startup not working

### ISSUE THREAD

**Issue by Mario-119** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#8]
Whenever I go to enable run at startup, the only thing that happens is that a terminal with root permissions opens in the program directory. No changes or anything seem to happen or be saved. The issue persists after multiple reboots as well. Currently on Ubuntu 21.04 and I'm using an MSI GE66 Raider

**Comment by YoCodingMonster** [comment]
Startup tab adds tasks to crontab in jobs but seems to not work properly..will get fixed soon
