### ISSUE TITLE
Failed to install on MSI GL75 Leopard 10SFR

### ISSUE THREAD

**Issue by diamondobama** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#9]
I followed every step in the ReadMe, including secure-boot disabling.

When I ran this on **Ubuntu** Distro
```sudo python3 GUI-MSI-DC-L.py```

I got an endless error of
 
> Traceback (most recent call last):
>   File "GUI-MSI-DC-L.py", line 330, in <module> monitoring_int(lable_c11, lable_c22, lable_c33, lable_g11, lable_g22, lable_g33, lable_m44, lable_m55)
>   File "GUI-MSI-DC-L.py", line 239, in monitoring_int with open(EC_IO_FILE,'r+b') as file:
> FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'
> Exception in thread Thread-1:

**Comment by YoCodingMonster** [comment]
Issue will be resolved within a week

**Comment by YoCodingMonster** [comment]
> I followed every step in the ReadMe, including secure-boot disabling.
> 
> When I ran this on **Ubuntu** Distro
> ```sudo python3 GUI-MSI-DC-L.py```
> 
> I got an endless error of
>  
> > Traceback (most recent call last):
> >   File "GUI-MSI-DC-L.py", line 330, in <module> monitoring_int(lable_c11, lable_c22, lable_c33, lable_g11, lable_g22, lable_g33, lable_m44, lable_m55)
> >   File "GUI-MSI-DC-L.py", line 239, in monitoring_int with open(EC_IO_FILE,'r+b') as file:
> > FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io'
> > Exception in thread Thread-1:
> 

Have you tried the latest release of this software?

**Comment by YoCodingMonster** [comment]
Restart the system after installing and try.....also check if secure boot has enabled itself automatically....after that reply that issue is solved or not so that i can investigate further

**Comment by YoCodingMonster** [comment]
> The installation failed even after a reboot.
> 
> Secure-boot stayed disabled on checking during the reboot.

can you please check and tell me if the file exist in path      '/sys/kernel/debug/ec/ec0/io'
if yes then i will need to change somethings in coding..
if no then install nautilus and get root access to folders manually and paste them in the specific folders....

DOWNLOADFOLDER/etc/modprobe.d/GUI-MSI-DC-L-ec_sys.conf TO /etc/modprobe.d/GUI-MSI-DC-L-ec_sys.conf"
iDOWNLOADFOLDER/etc/modules-load.d/GUI-MSI-DC-L-ec_sys.conf TO /etc/modules-load.d/GUI-MSI-DC-L-ec_sys.conf"

**Comment by RyanFlm** [comment]
Same here on Manjaro. I've double checked the requirements, but it fails with this exact error

**Comment by GabrielChouinardLetourneau** [comment]
> > > The installation failed even after a reboot.
> > > Secure-boot stayed disabled on checking during the reboot.
> > 
> > 
> > can you please check and tell me if the file exist in path '/sys/kernel/debug/ec/ec0/io'
> > if yes then i will need to change somethings in coding..
> > if no then install nautilus and get root access to folders manually and paste them in the specific folders....
> > DOWNLOADFOLDER/etc/modprobe.d/GUI-MSI-DC-L-ec_sys.conf TO /etc/modprobe.d/GUI-MSI-DC-L-ec_sys.conf"
> > iDOWNLOADFOLDER/etc/modules-load.d/GUI-MSI-DC-L-ec_sys.conf TO /etc/modules-load.d/GUI-MSI-DC-L-ec_sys.conf"
> 
> I had a similar error, and after the copy I can confirm the program runs.

What exactly did you do? I have the same issue with Ubuntu 20.04 LTS

**Comment by GabrielChouinardLetourneau** [comment]
> > > > > The installation failed even after a reboot.
> > > > > Secure-boot stayed disabled on checking during the reboot.
> > > > 
> > > > 
> > > > can you please check and tell me if the file exist in path '/sys/kernel/debug/ec/ec0/io'
> > > > if yes then i will need to change somethings in coding..
> > > > if no then install nautilus and get root access to folders manually and paste them in the specific folders....
> > > > DOWNLOADFOLDER/etc/modprobe.d/GUI-MSI-DC-L-ec_sys.conf TO /etc/modprobe.d/GUI-MSI-DC-L-ec_sys.conf"
> > > > iDOWNLOADFOLDER/etc/modules-load.d/GUI-MSI-DC-L-ec_sys.conf TO /etc/modules-load.d/GUI-MSI-DC-L-ec_sys.conf"
> > > 
> > > 
> > > I had a similar error, and after the copy I can confirm the program runs.
> > 
> > 
> > What exactly did you do? I have the same issue with Ubuntu 20.04 LTS
> 
> Just copied those two files as the author suggested into local `etc` folder and reboot.

Oh yeah got it! It does work for me too :) Thanks

**Comment by RyanFlm** [comment]
Also after I copied those two files and several reboots. The error still exists (FileNotFoundError: [Errno 2] No such file or directory: '/sys/kernel/debug/ec/ec0/io').
Maybe it is something with Arch. It seems like the other users all use an ubuntu distro.I got to search this.

**Comment by Special-Niewbie** [comment]
Hi @YoCodingMonster , 

If I can be helpfully on this I will be happy my friend....,Yesterday, I have to reinstall my Ubuntu 21.04 and today instead of to use the YoyPa software way, I have tried from "zero" to use your software. In fact the software it has the problems to create automatically the `io` file in '/sys/kernel/debug/ec/ec0/io'. Where in the way YoyPa it has similar situation but once you restart the system on next reboot I can proceed with the configuration. And with your software even if reboot it doesn't influence to create the `io` file. My question it's , it's that this kernel io file should exist by default? Or the YoyPa and Msi Dragon Center for Linux, it will create the `io` file once it run the softwares and all the files are installed into the related directories?

Unfortunately i saw late your replay above to solve this : 
```

DOWNLOADFOLDER/etc/modprobe.d/GUI-MSI-DC-L-ec_sys.conf TO /etc/modprobe.d/GUI-MSI-DC-L-ec_sys.conf
DOWNLOADFOLDER/etc/modules-load.d/GUI-MSI-DC-L-ec_sys.conf TO /etc/modules-load.d/GUI-MSI-DC-L-ec_sys.conf
```

And this time I went again to understand if it's MSI Dragon Center problem or some kind of silly bug from the system and I confirm that with YouPa software can create/ read the ec `io` file.

What can be the problem from MSI Dragon Center, please keep up that you are making really great job on it.

**Comment by YoCodingMonster** [comment]
> Hi @YoCodingMonster , 
> 
> If I can be helpfully on this I will be happy my friend....,Yesterday, I have to reinstall my Ubuntu 21.04 and today instead of to use the YoyPa software way, I have tried from "zero" to use your software. In fact the software it has the problems to create automatically the `io` file in '/sys/kernel/debug/ec/ec0/io'. Where in the way YoyPa it has similar situation but once you restart the system on next reboot I can proceed with the configuration. And with your software even if reboot it doesn't influence to create the `io` file. My question it's , it's that this kernel `io` file should exist by default? Or the YoyPa and Msi Dragon Center for Linux, it will create the `io` file once it run the softwares and all the files are installed into the related directories?
> 
> Unfortunately i saw late your replay above to solve this : 
> ```
> 
> DOWNLOADFOLDER/etc/modprobe.d/GUI-MSI-DC-L-ec_sys.conf TO /etc/modprobe.d/GUI-MSI-DC-L-ec_sys.conf
> DOWNLOADFOLDER/etc/modules-load.d/GUI-MSI-DC-L-ec_sys.conf TO /etc/modules-load.d/GUI-MSI-DC-L-ec_sys.conf
> ```
> 
> And this time I went again to understand if it's MSI Dragon Center problem or some kind of silly bug from the system and I confirm that with YouPa software can create/ read the ec `io` file.
> 
> What can be the problem from MSI Dragon Center, please keep up that you are making really great job on it.

In some ubuntu based devices... The IO files you are talking about are hidden...and the software both yoypa and mai dragon center for Linux..just make them readable by passing an argument in kernal which opens them to user...

But this is not 100% accurate in my software...you need to install dependencies and nautilus and just do the readme XD things to get it done...properly...
I am working on the release this Monday which I think will fix the issue and also some major updates!!

**Comment by Special-Niewbie** [comment]
Thanks to reply, in fact from read file I have installed all the libs that you request but i didn't  install the `nautilus-admin` because I was sure that Ubuntu Distro it has installed by default , but in fact I'm wrong because just then i checked and it's true that Ubuntu it has Nautilus installed with some extensions but I'm missing the `nautilus-admin` libs, you are totally right!!!

Thanks again, I will be waiting for the next updates anxiously, and another thing that comes in my mind, before MSI Dragon Center will change the values into the `io` file, will be great if it let you save a backup file of it with inside wrote the old and new parameters modification.... ;)

:+1:

**Comment by YoCodingMonster** [comment]
sure @Special-Niewbie , will impliment it in ver 1.4.
currently working config file which will be version 1.3.x

**Comment by Special-Niewbie** [comment]
> sure @Special-Niewbie , will impliment it in ver 1.4.
> currently working config file which will be version 1.3.x

Love you man, thank you so so much ;) you will be a legend for MSI Laptop owners....

**Comment by diamondobama** [comment]
I'm able to run the latest version on my Laptop. Thank you
